### ISSUE TITLE
After updating Anki, I can't add audios to words

### ISSUE THREAD

**Issue by SueHua2020** [kelciour/awesometts-anki-addon#32] opened 2020-06-05 05:52 UTC
When using Microsoft Speech API JScript: 
The following problems were encountered:
- No speakable text is present
- The input file to transcode to an MP3 could not be found. Please report this problem if it persists.

When using Google Cloud Text-to- Speech: 
The following problems were encountered:
- No speakable text is present
- 'API Key required to access googletts'

**Comment by evandrocoan** [comment] 2020-06-05 15:28
What is your updated Anki version? Can you show screenshots of the errors?

**Comment by SueHua2020** [comment] 2020-06-06 03:19
> What is your updated Anki version? Can you show screenshots of the errors?

when the issue first came, the version was 2.1.20-windows, then I installed 2.1.26, the problem still exist.

<img width="491" alt="version" src="https://user-images.githubusercontent.com/66459195/83934980-978b6380-a7e7-11ea-81c3-81e27c2334dc.PNG">

<img width="376" alt="Capture 1" src="https://user-images.githubusercontent.com/66459195/83934981-9b1eea80-a7e7-11ea-9bf3-67ce5c10e717.PNG">

<img width="373" alt="Capture 2" src="https://user-images.githubusercontent.com/66459195/83934983-9d814480-a7e7-11ea-807f-094d104269b8.PNG">

**Comment by evandrocoan** [comment] 2020-06-06 15:37
What are the steps you do to get on these errors?

i.e., 

1. I open Anki
1. I open the browser window
1. I select these ... cards
1. I hit AwesomeTTS button
1. I select the field XXX

Are your fields empty? Which one is the card you are trying use?

**Comment by SueHua2020** [comment] 2020-06-07 03:19
> What are the steps you do to get on these errors?
> 
> i.e.,
> 
> 1. I open Anki
> 2. I open the browser window
> 3. I select these ... cards
> 4. I hit AwesomeTTS button
> 5. I select the field XXX
> 
> Are your fields empty? Which one is the card you are trying use?

It worked well before; until I tried to remove all the audio and then re-add the audio, it never worked again
Steps are as follows:

![steps mp4_20200607_110331030](https://user-images.githubusercontent.com/66459195/83959379-f10a9580-a8ae-11ea-8773-26ff537152ea.jpg)

![steps mp4_20200607_110344547](https://user-images.githubusercontent.com/66459195/83959383-f667e000-a8ae-11ea-9b1b-d26e3e9e140b.jpg)

![steps mp4_20200607_110346957](https://user-images.githubusercontent.com/66459195/83959388-fcf65780-a8ae-11ea-8c39-90b969706667.jpg)

![steps mp4_20200607_110349028](https://user-images.githubusercontent.com/66459195/83959391-041d6580-a8af-11ea-8544-3310e77286c4.jpg)

![steps mp4_20200607_110350199](https://user-images.githubusercontent.com/66459195/83959394-08e21980-a8af-11ea-92ce-bbc4a38f580e.jpg)

![steps mp4_20200607_110351021](https://user-images.githubusercontent.com/66459195/83959398-0ed7fa80-a8af-11ea-8a8b-f326c24646cf.jpg)

![steps mp4_20200607_110353517](https://user-images.githubusercontent.com/66459195/83959404-17303580-a8af-11ea-9982-35d400853a28.jpg)

![steps mp4_20200607_110355306](https://user-images.githubusercontent.com/66459195/83959406-1f887080-a8af-11ea-8378-4828a5b1f980.jpg)

![steps mp4_20200607_110402134](https://user-images.githubusercontent.com/66459195/83959411-26af7e80-a8af-11ea-9cee-b0b540488c88.jpg)

![steps mp4_20200607_110405786](https://user-images.githubusercontent.com/66459195/83959413-2adb9c00-a8af-11ea-9565-69202bdd53d4.jpg)

![steps mp4_20200607_110406938](https://user-images.githubusercontent.com/66459195/83959414-316a1380-a8af-11ea-8908-4ff555c02528.jpg)

![steps mp4_20200607_110410306](https://user-images.githubusercontent.com/66459195/83959415-37f88b00-a8af-11ea-8202-df9d0ecd7b86.jpg)


I can’t understand the question about “Which one is the card you are trying use?
”, but the template I used came from netizens sharing：

**Comment by evandrocoan** [comment] 2020-06-07 03:54
> When using Google Cloud Text-to- Speech:
> The following problems were encountered:
> 
> * No speakable text is present
> * 'API Key required to access googletts'

What do you mean by `'API Key required to access googletts'`?

Before this step you forgot to show what options you had selected:

> ![](https://user-images.githubusercontent.com/66459195/83959404-17303580-a8af-11ea-9982-35d400853a28.jpg)

**Comment by SueHua2020** [comment] 2020-06-07 04:06
> > When using Google Cloud Text-to- Speech:
> > The following problems were encountered:
> > 
> > * No speakable text is present
> > * 'API Key required to access googletts'
> 
> What do you mean by `'API Key required to access googletts'`?
> 
> Before this step you forgot to show what options you had selected:
> 
> > ![](https://user-images.githubusercontent.com/66459195/83959404-17303580-a8af-11ea-9982-35d400853a28.jpg)

'API Key required to access googletts` is the result when changing "1" to "2" as shown below,

![image](https://user-images.githubusercontent.com/66459195/83960100-56628480-a8b7-11ea-9269-55c5d5c7b3e3.png)

**Comment by evandrocoan** [comment] 2020-06-07 21:19
Are you selecting the right field?

That error indicates the field you are selecting is empty.

![image](https://user-images.githubusercontent.com/5332158/83980345-52505a00-a8eb-11ea-8894-94edbc941b94.png)

If that is not the case, can you export a single card/note of your collection so I can try to reproduce the problem on my computer?


> 'API Key required to access googletts` is the result when changing "1" to "2" as shown below,

While Microsoft Speech is free, Google TTS is a paid service. You should get an API key for your account and put it there. Please see:

1. https://github.com/kelciour/awesometts-anki-addon/issues/29 - 403 Client Error
1. https://ankiweb.net/shared/info/814349176 - HOW TO USE

**Comment by SueHua2020** [comment] 2020-06-08 02:19
> Are you selecting the right field?
> 
> That error indicates the field you are selecting is empty.
> 
> ![image](https://user-images.githubusercontent.com/5332158/83980345-52505a00-a8eb-11ea-8894-94edbc941b94.png)
> 
> If that is not the case, can you export a single card/note of your collection so I can try to reproduce the problem on my computer?
> 
> > 'API Key required to access googletts` is the result when changing "1" to "2" as shown below,
> 
> While Microsoft Speech is free, Google TTS is a paid service. You should get an API key for your account and put it there. Please see:
> 
> 1. #29 - 403 Client Error
> 2. https://ankiweb.net/shared/info/814349176 - HOW TO USE

The area pointed by the arrow does not affect the result, it is the same result of other options. I tried to import one single card, as follows,

[1111111.zip](https://github.com/kelciour/awesometts-anki-addon/files/4743555/1111111.zip)

Thank you!

**Comment by kelciour** [comment] 2020-07-07 17:56
@evandrocoan, thank you for going out of the way to help!

@SueHua2020, I've imported 1111111.zip and looking at the screenshots it looks like you selected `发音` as a source field, but it's empty in your deck and AwesomeTTS can't generate any audio ("No speakable text is present"). Please use a different field as a source field for AwesomeTTS.

I'm closing the issue, but if something is not clear, just leave a comment or open a new issue.

**Closed by kelciour** 2020-07-07 17:56 UTC
